// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQAxgWzCwgJUf2e4wQ9kAJEqCCrLExz4g',
    appId: '1:99799684958:web:e3e7377f753775b614e1cf',
    messagingSenderId: '99799684958',
    projectId: 'meal-app-finki',
    authDomain: 'meal-app-finki.firebaseapp.com',
    storageBucket: 'meal-app-finki.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEkMoP6OkTBjNsFQidIDUH5WLxBKxyuLM',
    appId: '1:99799684958:android:49dbdb6f0eefa69e14e1cf',
    messagingSenderId: '99799684958',
    projectId: 'meal-app-finki',
    storageBucket: 'meal-app-finki.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUSGF1SJ8qk4-zuHCdnmr0B7ZvamYBq8Y',
    appId: '1:99799684958:ios:17c8ac148f9d530e14e1cf',
    messagingSenderId: '99799684958',
    projectId: 'meal-app-finki',
    storageBucket: 'meal-app-finki.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUSGF1SJ8qk4-zuHCdnmr0B7ZvamYBq8Y',
    appId: '1:99799684958:ios:17c8ac148f9d530e14e1cf',
    messagingSenderId: '99799684958',
    projectId: 'meal-app-finki',
    storageBucket: 'meal-app-finki.firebasestorage.app',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQAxgWzCwgJUf2e4wQ9kAJEqCCrLExz4g',
    appId: '1:99799684958:web:4f1517a1f73e702a14e1cf',
    messagingSenderId: '99799684958',
    projectId: 'meal-app-finki',
    authDomain: 'meal-app-finki.firebaseapp.com',
    storageBucket: 'meal-app-finki.firebasestorage.app',
  );
}
